/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'recordId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberId = IDL.Text;
export const RecodingId = IDL.Text;
export const LabelEntityId = IDL.Text;
export const ArtistDevelopmentId = IDL.Text;
export const PublishingId = IDL.Text;
export const CreateArtistDevelopmentRequest = IDL.Record({
  'relatedRecordingProjects' : IDL.Vec(RecodingId),
  'relatedLabelEntities' : IDL.Vec(LabelEntityId),
  'artistId' : IDL.Text,
  'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
  'relatedMemberships' : IDL.Vec(MemberId),
  'goals' : IDL.Vec(IDL.Text),
  'plans' : IDL.Vec(IDL.Text),
  'internalNotes' : IDL.Text,
  'relatedPublishing' : IDL.Vec(PublishingId),
  'milestones' : IDL.Vec(IDL.Text),
});
export const CreateArtistDevelopmentResponse = IDL.Record({
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'relatedLabelEntities' : IDL.Vec(LabelEntityId),
  'artistId' : IDL.Text,
  'created_at' : Time,
  'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
  'relatedMemberships' : IDL.Vec(MemberId),
  'goals' : IDL.Vec(IDL.Text),
  'plans' : IDL.Vec(IDL.Text),
  'internalNotes' : IDL.Text,
  'relatedPublishing' : IDL.Vec(PublishingId),
  'milestones' : IDL.Vec(IDL.Text),
});
export const T = IDL.Variant({
  'applicant' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'paused' : IDL.Null,
});
export const MembershipProfile = IDL.Record({
  'id' : MemberId,
  'agreements' : IDL.Vec(IDL.Text),
  'status' : T,
  'updated_at' : Time,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'created_at' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
});
export const CreatePublishingWorkRequest = IDL.Record({
  'title' : IDL.Text,
  'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'linkedProjects' : IDL.Vec(RecodingId),
  'isrc' : IDL.Opt(IDL.Text),
  'iswc' : IDL.Opt(IDL.Text),
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'contributors' : IDL.Vec(IDL.Text),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const PublishingWork = IDL.Record({
  'id' : PublishingId,
  'title' : IDL.Text,
  'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'linkedProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'isrc' : IDL.Opt(IDL.Text),
  'iswc' : IDL.Opt(IDL.Text),
  'created_at' : Time,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'contributors' : IDL.Vec(IDL.Text),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const ProjectStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'archived' : IDL.Null,
});
export const CreateRecordingProjectRequest = IDL.Record({
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'sessionDate' : Time,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'assetReferences' : IDL.Vec(IDL.Text),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const RecordingProject = IDL.Record({
  'id' : RecodingId,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'sessionDate' : Time,
  'owner' : IDL.Principal,
  'created_at' : Time,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'assetReferences' : IDL.Vec(IDL.Text),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const CreateReleaseRequest = IDL.Record({
  'title' : IDL.Text,
  'workflowChecklist' : IDL.Vec(IDL.Text),
  'keyDates' : IDL.Vec(IDL.Text),
  'owners' : IDL.Vec(IDL.Text),
  'linkedProjects' : IDL.Vec(RecodingId),
  'tracklist' : IDL.Vec(IDL.Text),
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedMembers' : IDL.Vec(MemberId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'releaseType' : IDL.Text,
});
export const Release = IDL.Record({
  'id' : LabelEntityId,
  'title' : IDL.Text,
  'workflowChecklist' : IDL.Vec(IDL.Text),
  'keyDates' : IDL.Vec(IDL.Text),
  'owners' : IDL.Vec(IDL.Text),
  'linkedProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'tracklist' : IDL.Vec(IDL.Text),
  'created_at' : Time,
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedMembers' : IDL.Vec(MemberId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'releaseType' : IDL.Text,
});
export const ArtistDevelopment = IDL.Record({
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'relatedLabelEntities' : IDL.Vec(LabelEntityId),
  'artistId' : IDL.Text,
  'created_at' : Time,
  'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
  'relatedMemberships' : IDL.Vec(MemberId),
  'goals' : IDL.Vec(IDL.Text),
  'plans' : IDL.Vec(IDL.Text),
  'internalNotes' : IDL.Text,
  'relatedPublishing' : IDL.Vec(PublishingId),
  'milestones' : IDL.Vec(IDL.Text),
});
export const MembershipTier = IDL.Record({
  'fee' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const Membership = IDL.Record({
  'linkedProjects' : IDL.Vec(RecodingId),
  'tier' : MembershipTier,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'profile' : MembershipProfile,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SignedInUser = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const ChangeEvent = IDL.Record({
  'id' : IDL.Nat,
  'operationType' : IDL.Variant({
    'link' : IDL.Null,
    'create' : IDL.Null,
    'update' : IDL.Null,
  }),
  'author' : IDL.Principal,
  'changedFields' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'recordId' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalMemberships' : IDL.Nat,
  'membershipStatusCounts' : IDL.Vec(IDL.Tuple(T, IDL.Nat)),
  'totalRecordingProjects' : IDL.Nat,
  'projectStatusCounts' : IDL.Vec(IDL.Tuple(ProjectStatus, IDL.Nat)),
  'totalPublishingWorks' : IDL.Nat,
  'totalArtistDevelopment' : IDL.Nat,
  'releaseTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalReleases' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeleteMembershipProfiles' : IDL.Func(
      [IDL.Vec(MemberId)],
      [
        IDL.Record({
          'deleted' : IDL.Vec(MemberId),
          'failed' : IDL.Vec(MemberId),
        }),
      ],
      [],
    ),
  'createArtistDevelopment' : IDL.Func(
      [CreateArtistDevelopmentRequest],
      [CreateArtistDevelopmentResponse],
      [],
    ),
  'createMembershipProfile' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text],
      [MembershipProfile],
      [],
    ),
  'createPublishingWork' : IDL.Func(
      [CreatePublishingWorkRequest],
      [PublishingWork],
      [],
    ),
  'createRecordingProject' : IDL.Func(
      [CreateRecordingProjectRequest],
      [RecordingProject],
      [],
    ),
  'createRelease' : IDL.Func([CreateReleaseRequest], [Release], []),
  'deleteArtistDevelopment' : IDL.Func([ArtistDevelopmentId], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteMembership' : IDL.Func([MemberId], [], []),
  'deletePublishingWork' : IDL.Func([PublishingId], [], []),
  'deleteRecordingProject' : IDL.Func([RecodingId], [], []),
  'deleteRelease' : IDL.Func([LabelEntityId], [], []),
  'duplicateArtistDevelopment' : IDL.Func(
      [ArtistDevelopmentId],
      [ArtistDevelopment],
      [],
    ),
  'duplicateMembership' : IDL.Func([MemberId], [Membership], []),
  'duplicatePublishingWork' : IDL.Func([PublishingId], [PublishingWork], []),
  'duplicateRecordingProject' : IDL.Func([RecodingId], [RecordingProject], []),
  'duplicateRelease' : IDL.Func([LabelEntityId], [Release], []),
  'getAllArtistDevelopments' : IDL.Func(
      [],
      [IDL.Vec(ArtistDevelopment)],
      ['query'],
    ),
  'getAllKnownUsers' : IDL.Func([], [IDL.Vec(SignedInUser)], ['query']),
  'getAllMembershipProfiles' : IDL.Func(
      [],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getAllPublishingWorks' : IDL.Func([], [IDL.Vec(PublishingWork)], ['query']),
  'getAllRecordingProjects' : IDL.Func(
      [],
      [IDL.Vec(RecordingProject)],
      ['query'],
    ),
  'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getArtistDevelopment' : IDL.Func(
      [ArtistDevelopmentId],
      [ArtistDevelopment],
      ['query'],
    ),
  'getCallerArtistDevelopments' : IDL.Func(
      [],
      [IDL.Vec(ArtistDevelopment)],
      ['query'],
    ),
  'getCallerMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'getCallerPublishingWorks' : IDL.Func(
      [],
      [IDL.Vec(PublishingWork)],
      ['query'],
    ),
  'getCallerRecordingProjects' : IDL.Func(
      [],
      [IDL.Vec(RecordingProject)],
      ['query'],
    ),
  'getCallerReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangeHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChangeEvent)], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
  'getMembershipProfile' : IDL.Func([MemberId], [MembershipProfile], ['query']),
  'getMembershipProfilesByStatus' : IDL.Func(
      [T],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getPublishingWork' : IDL.Func([PublishingId], [PublishingWork], ['query']),
  'getRecordingProject' : IDL.Func([RecodingId], [RecordingProject], ['query']),
  'getRelease' : IDL.Func([LabelEntityId], [Release], ['query']),
  'getRemainingRolloutSteps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateArtistDevelopment' : IDL.Func(
      [ArtistDevelopmentId, CreateArtistDevelopmentRequest],
      [ArtistDevelopment],
      [],
    ),
  'updateKnownUserRole' : IDL.Func([], [], []),
  'updateMembership' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text, T],
      [MembershipProfile],
      [],
    ),
  'updateMembershipLinks' : IDL.Func(
      [
        MemberId,
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'updateMembershipProfileFields' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text],
      [MembershipProfile],
      [],
    ),
  'updateMembershipStatus' : IDL.Func([MemberId, T], [MembershipProfile], []),
  'updatePublishingWork' : IDL.Func(
      [PublishingId, CreatePublishingWorkRequest],
      [PublishingWork],
      [],
    ),
  'updateRecordingProject' : IDL.Func(
      [RecodingId, CreateRecordingProjectRequest],
      [RecordingProject],
      [],
    ),
  'updateRelease' : IDL.Func(
      [LabelEntityId, CreateReleaseRequest],
      [Release],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'recordId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberId = IDL.Text;
  const RecodingId = IDL.Text;
  const LabelEntityId = IDL.Text;
  const ArtistDevelopmentId = IDL.Text;
  const PublishingId = IDL.Text;
  const CreateArtistDevelopmentRequest = IDL.Record({
    'relatedRecordingProjects' : IDL.Vec(RecodingId),
    'relatedLabelEntities' : IDL.Vec(LabelEntityId),
    'artistId' : IDL.Text,
    'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
    'relatedMemberships' : IDL.Vec(MemberId),
    'goals' : IDL.Vec(IDL.Text),
    'plans' : IDL.Vec(IDL.Text),
    'internalNotes' : IDL.Text,
    'relatedPublishing' : IDL.Vec(PublishingId),
    'milestones' : IDL.Vec(IDL.Text),
  });
  const CreateArtistDevelopmentResponse = IDL.Record({
    'id' : ArtistDevelopmentId,
    'relatedRecordingProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'relatedLabelEntities' : IDL.Vec(LabelEntityId),
    'artistId' : IDL.Text,
    'created_at' : Time,
    'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
    'relatedMemberships' : IDL.Vec(MemberId),
    'goals' : IDL.Vec(IDL.Text),
    'plans' : IDL.Vec(IDL.Text),
    'internalNotes' : IDL.Text,
    'relatedPublishing' : IDL.Vec(PublishingId),
    'milestones' : IDL.Vec(IDL.Text),
  });
  const T = IDL.Variant({
    'applicant' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'paused' : IDL.Null,
  });
  const MembershipProfile = IDL.Record({
    'id' : MemberId,
    'agreements' : IDL.Vec(IDL.Text),
    'status' : T,
    'updated_at' : Time,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'created_at' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
  });
  const CreatePublishingWorkRequest = IDL.Record({
    'title' : IDL.Text,
    'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'linkedProjects' : IDL.Vec(RecodingId),
    'isrc' : IDL.Opt(IDL.Text),
    'iswc' : IDL.Opt(IDL.Text),
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'contributors' : IDL.Vec(IDL.Text),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const PublishingWork = IDL.Record({
    'id' : PublishingId,
    'title' : IDL.Text,
    'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'linkedProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'isrc' : IDL.Opt(IDL.Text),
    'iswc' : IDL.Opt(IDL.Text),
    'created_at' : Time,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'contributors' : IDL.Vec(IDL.Text),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const ProjectStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'archived' : IDL.Null,
  });
  const CreateRecordingProjectRequest = IDL.Record({
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'sessionDate' : Time,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'assetReferences' : IDL.Vec(IDL.Text),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const RecordingProject = IDL.Record({
    'id' : RecodingId,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'sessionDate' : Time,
    'owner' : IDL.Principal,
    'created_at' : Time,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'assetReferences' : IDL.Vec(IDL.Text),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const CreateReleaseRequest = IDL.Record({
    'title' : IDL.Text,
    'workflowChecklist' : IDL.Vec(IDL.Text),
    'keyDates' : IDL.Vec(IDL.Text),
    'owners' : IDL.Vec(IDL.Text),
    'linkedProjects' : IDL.Vec(RecodingId),
    'tracklist' : IDL.Vec(IDL.Text),
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedMembers' : IDL.Vec(MemberId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'releaseType' : IDL.Text,
  });
  const Release = IDL.Record({
    'id' : LabelEntityId,
    'title' : IDL.Text,
    'workflowChecklist' : IDL.Vec(IDL.Text),
    'keyDates' : IDL.Vec(IDL.Text),
    'owners' : IDL.Vec(IDL.Text),
    'linkedProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'tracklist' : IDL.Vec(IDL.Text),
    'created_at' : Time,
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedMembers' : IDL.Vec(MemberId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'releaseType' : IDL.Text,
  });
  const ArtistDevelopment = IDL.Record({
    'id' : ArtistDevelopmentId,
    'relatedRecordingProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'relatedLabelEntities' : IDL.Vec(LabelEntityId),
    'artistId' : IDL.Text,
    'created_at' : Time,
    'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
    'relatedMemberships' : IDL.Vec(MemberId),
    'goals' : IDL.Vec(IDL.Text),
    'plans' : IDL.Vec(IDL.Text),
    'internalNotes' : IDL.Text,
    'relatedPublishing' : IDL.Vec(PublishingId),
    'milestones' : IDL.Vec(IDL.Text),
  });
  const MembershipTier = IDL.Record({
    'fee' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const Membership = IDL.Record({
    'linkedProjects' : IDL.Vec(RecodingId),
    'tier' : MembershipTier,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'profile' : MembershipProfile,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const SignedInUser = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const ChangeEvent = IDL.Record({
    'id' : IDL.Nat,
    'operationType' : IDL.Variant({
      'link' : IDL.Null,
      'create' : IDL.Null,
      'update' : IDL.Null,
    }),
    'author' : IDL.Principal,
    'changedFields' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'recordId' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalMemberships' : IDL.Nat,
    'membershipStatusCounts' : IDL.Vec(IDL.Tuple(T, IDL.Nat)),
    'totalRecordingProjects' : IDL.Nat,
    'projectStatusCounts' : IDL.Vec(IDL.Tuple(ProjectStatus, IDL.Nat)),
    'totalPublishingWorks' : IDL.Nat,
    'totalArtistDevelopment' : IDL.Nat,
    'releaseTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalReleases' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeleteMembershipProfiles' : IDL.Func(
        [IDL.Vec(MemberId)],
        [
          IDL.Record({
            'deleted' : IDL.Vec(MemberId),
            'failed' : IDL.Vec(MemberId),
          }),
        ],
        [],
      ),
    'createArtistDevelopment' : IDL.Func(
        [CreateArtistDevelopmentRequest],
        [CreateArtistDevelopmentResponse],
        [],
      ),
    'createMembershipProfile' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text],
        [MembershipProfile],
        [],
      ),
    'createPublishingWork' : IDL.Func(
        [CreatePublishingWorkRequest],
        [PublishingWork],
        [],
      ),
    'createRecordingProject' : IDL.Func(
        [CreateRecordingProjectRequest],
        [RecordingProject],
        [],
      ),
    'createRelease' : IDL.Func([CreateReleaseRequest], [Release], []),
    'deleteArtistDevelopment' : IDL.Func([ArtistDevelopmentId], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteMembership' : IDL.Func([MemberId], [], []),
    'deletePublishingWork' : IDL.Func([PublishingId], [], []),
    'deleteRecordingProject' : IDL.Func([RecodingId], [], []),
    'deleteRelease' : IDL.Func([LabelEntityId], [], []),
    'duplicateArtistDevelopment' : IDL.Func(
        [ArtistDevelopmentId],
        [ArtistDevelopment],
        [],
      ),
    'duplicateMembership' : IDL.Func([MemberId], [Membership], []),
    'duplicatePublishingWork' : IDL.Func([PublishingId], [PublishingWork], []),
    'duplicateRecordingProject' : IDL.Func(
        [RecodingId],
        [RecordingProject],
        [],
      ),
    'duplicateRelease' : IDL.Func([LabelEntityId], [Release], []),
    'getAllArtistDevelopments' : IDL.Func(
        [],
        [IDL.Vec(ArtistDevelopment)],
        ['query'],
      ),
    'getAllKnownUsers' : IDL.Func([], [IDL.Vec(SignedInUser)], ['query']),
    'getAllMembershipProfiles' : IDL.Func(
        [],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getAllPublishingWorks' : IDL.Func(
        [],
        [IDL.Vec(PublishingWork)],
        ['query'],
      ),
    'getAllRecordingProjects' : IDL.Func(
        [],
        [IDL.Vec(RecordingProject)],
        ['query'],
      ),
    'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getArtistDevelopment' : IDL.Func(
        [ArtistDevelopmentId],
        [ArtistDevelopment],
        ['query'],
      ),
    'getCallerArtistDevelopments' : IDL.Func(
        [],
        [IDL.Vec(ArtistDevelopment)],
        ['query'],
      ),
    'getCallerMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'getCallerPublishingWorks' : IDL.Func(
        [],
        [IDL.Vec(PublishingWork)],
        ['query'],
      ),
    'getCallerRecordingProjects' : IDL.Func(
        [],
        [IDL.Vec(RecordingProject)],
        ['query'],
      ),
    'getCallerReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangeHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChangeEvent)],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
    'getMembershipProfile' : IDL.Func(
        [MemberId],
        [MembershipProfile],
        ['query'],
      ),
    'getMembershipProfilesByStatus' : IDL.Func(
        [T],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getPublishingWork' : IDL.Func([PublishingId], [PublishingWork], ['query']),
    'getRecordingProject' : IDL.Func(
        [RecodingId],
        [RecordingProject],
        ['query'],
      ),
    'getRelease' : IDL.Func([LabelEntityId], [Release], ['query']),
    'getRemainingRolloutSteps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateArtistDevelopment' : IDL.Func(
        [ArtistDevelopmentId, CreateArtistDevelopmentRequest],
        [ArtistDevelopment],
        [],
      ),
    'updateKnownUserRole' : IDL.Func([], [], []),
    'updateMembership' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text, T],
        [MembershipProfile],
        [],
      ),
    'updateMembershipLinks' : IDL.Func(
        [
          MemberId,
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'updateMembershipProfileFields' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text],
        [MembershipProfile],
        [],
      ),
    'updateMembershipStatus' : IDL.Func([MemberId, T], [MembershipProfile], []),
    'updatePublishingWork' : IDL.Func(
        [PublishingId, CreatePublishingWorkRequest],
        [PublishingWork],
        [],
      ),
    'updateRecordingProject' : IDL.Func(
        [RecodingId, CreateRecordingProjectRequest],
        [RecordingProject],
        [],
      ),
    'updateRelease' : IDL.Func(
        [LabelEntityId, CreateReleaseRequest],
        [Release],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };