/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ArtistDevelopment {
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : Array<RecodingId>,
  'owner' : Principal,
  'relatedLabelEntities' : Array<LabelEntityId>,
  'artistId' : string,
  'created_at' : Time,
  'relatedArtistDevelopment' : Array<ArtistDevelopmentId>,
  'relatedMemberships' : Array<MemberId>,
  'goals' : Array<string>,
  'plans' : Array<string>,
  'internalNotes' : string,
  'relatedPublishing' : Array<PublishingId>,
  'milestones' : Array<string>,
}
export type ArtistDevelopmentId = string;
export interface ChangeEvent {
  'id' : bigint,
  'operationType' : { 'link' : null } |
    { 'create' : null } |
    { 'update' : null },
  'author' : Principal,
  'changedFields' : Array<string>,
  'timestamp' : bigint,
  'recordId' : string,
}
export interface Comment {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
  'author' : Principal,
  'recordId' : string,
}
export interface CreateArtistDevelopmentRequest {
  'relatedRecordingProjects' : Array<RecodingId>,
  'relatedLabelEntities' : Array<LabelEntityId>,
  'artistId' : string,
  'relatedArtistDevelopment' : Array<ArtistDevelopmentId>,
  'relatedMemberships' : Array<MemberId>,
  'goals' : Array<string>,
  'plans' : Array<string>,
  'internalNotes' : string,
  'relatedPublishing' : Array<PublishingId>,
  'milestones' : Array<string>,
}
export interface CreateArtistDevelopmentResponse {
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : Array<RecodingId>,
  'owner' : Principal,
  'relatedLabelEntities' : Array<LabelEntityId>,
  'artistId' : string,
  'created_at' : Time,
  'relatedArtistDevelopment' : Array<ArtistDevelopmentId>,
  'relatedMemberships' : Array<MemberId>,
  'goals' : Array<string>,
  'plans' : Array<string>,
  'internalNotes' : string,
  'relatedPublishing' : Array<PublishingId>,
  'milestones' : Array<string>,
}
export interface CreatePublishingWorkRequest {
  'title' : string,
  'ownershipSplits' : Array<[string, bigint]>,
  'linkedProjects' : Array<RecodingId>,
  'isrc' : [] | [string],
  'iswc' : [] | [string],
  'linkedReleases' : Array<LabelEntityId>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'registrationStatus' : string,
  'contributors' : Array<string>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export interface CreateRecordingProjectRequest {
  'status' : ProjectStatus,
  'title' : string,
  'participants' : Array<string>,
  'sessionDate' : Time,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'assetReferences' : Array<string>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export interface CreateReleaseRequest {
  'title' : string,
  'workflowChecklist' : Array<string>,
  'keyDates' : Array<string>,
  'owners' : Array<string>,
  'linkedProjects' : Array<RecodingId>,
  'tracklist' : Array<string>,
  'linkedWorks' : Array<PublishingId>,
  'linkedMembers' : Array<MemberId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'releaseType' : string,
}
export interface DashboardStats {
  'totalMemberships' : bigint,
  'membershipStatusCounts' : Array<[T, bigint]>,
  'totalRecordingProjects' : bigint,
  'projectStatusCounts' : Array<[ProjectStatus, bigint]>,
  'totalPublishingWorks' : bigint,
  'totalArtistDevelopment' : bigint,
  'releaseTypeCounts' : Array<[string, bigint]>,
  'totalReleases' : bigint,
}
export type LabelEntityId = string;
export type MemberId = string;
export interface Membership {
  'linkedProjects' : Array<RecodingId>,
  'tier' : MembershipTier,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'profile' : MembershipProfile,
}
export interface MembershipProfile {
  'id' : MemberId,
  'agreements' : Array<string>,
  'status' : T,
  'updated_at' : Time,
  'principal' : Principal,
  'name' : string,
  'tier' : string,
  'created_at' : Time,
  'email' : string,
  'notes' : string,
}
export interface MembershipTier {
  'fee' : bigint,
  'name' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export type ProjectStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'archived' : null };
export type PublishingId = string;
export interface PublishingWork {
  'id' : PublishingId,
  'title' : string,
  'ownershipSplits' : Array<[string, bigint]>,
  'linkedProjects' : Array<RecodingId>,
  'owner' : Principal,
  'isrc' : [] | [string],
  'iswc' : [] | [string],
  'created_at' : Time,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'registrationStatus' : string,
  'contributors' : Array<string>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export type RecodingId = string;
export interface RecordingProject {
  'id' : RecodingId,
  'status' : ProjectStatus,
  'title' : string,
  'participants' : Array<string>,
  'sessionDate' : Time,
  'owner' : Principal,
  'created_at' : Time,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'assetReferences' : Array<string>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export interface Release {
  'id' : LabelEntityId,
  'title' : string,
  'workflowChecklist' : Array<string>,
  'keyDates' : Array<string>,
  'owners' : Array<string>,
  'linkedProjects' : Array<RecodingId>,
  'owner' : Principal,
  'tracklist' : Array<string>,
  'created_at' : Time,
  'linkedWorks' : Array<PublishingId>,
  'linkedMembers' : Array<MemberId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'releaseType' : string,
}
export interface SignedInUser {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export type T = { 'applicant' : null } |
  { 'active' : null } |
  { 'inactive' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteMembershipProfiles' : ActorMethod<
    [Array<MemberId>],
    { 'deleted' : Array<MemberId>, 'failed' : Array<MemberId> }
  >,
  'createArtistDevelopment' : ActorMethod<
    [CreateArtistDevelopmentRequest],
    CreateArtistDevelopmentResponse
  >,
  'createMembershipProfile' : ActorMethod<
    [MemberId, string, string],
    MembershipProfile
  >,
  'createPublishingWork' : ActorMethod<
    [CreatePublishingWorkRequest],
    PublishingWork
  >,
  'createRecordingProject' : ActorMethod<
    [CreateRecordingProjectRequest],
    RecordingProject
  >,
  'createRelease' : ActorMethod<[CreateReleaseRequest], Release>,
  'deleteArtistDevelopment' : ActorMethod<[ArtistDevelopmentId], undefined>,
  'deleteComment' : ActorMethod<[string, bigint], undefined>,
  'deleteMembership' : ActorMethod<[MemberId], undefined>,
  'deletePublishingWork' : ActorMethod<[PublishingId], undefined>,
  'deleteRecordingProject' : ActorMethod<[RecodingId], undefined>,
  'deleteRelease' : ActorMethod<[LabelEntityId], undefined>,
  'duplicateArtistDevelopment' : ActorMethod<
    [ArtistDevelopmentId],
    ArtistDevelopment
  >,
  'duplicateMembership' : ActorMethod<[MemberId], Membership>,
  'duplicatePublishingWork' : ActorMethod<[PublishingId], PublishingWork>,
  'duplicateRecordingProject' : ActorMethod<[RecodingId], RecordingProject>,
  'duplicateRelease' : ActorMethod<[LabelEntityId], Release>,
  'getAllArtistDevelopments' : ActorMethod<[], Array<ArtistDevelopment>>,
  'getAllKnownUsers' : ActorMethod<[], Array<SignedInUser>>,
  'getAllMembershipProfiles' : ActorMethod<[], Array<MembershipProfile>>,
  'getAllPublishingWorks' : ActorMethod<[], Array<PublishingWork>>,
  'getAllRecordingProjects' : ActorMethod<[], Array<RecordingProject>>,
  'getAllReleases' : ActorMethod<[], Array<Release>>,
  'getArtistDevelopment' : ActorMethod<
    [ArtistDevelopmentId],
    ArtistDevelopment
  >,
  'getCallerArtistDevelopments' : ActorMethod<[], Array<ArtistDevelopment>>,
  'getCallerMemberships' : ActorMethod<[], Array<Membership>>,
  'getCallerPublishingWorks' : ActorMethod<[], Array<PublishingWork>>,
  'getCallerRecordingProjects' : ActorMethod<[], Array<RecordingProject>>,
  'getCallerReleases' : ActorMethod<[], Array<Release>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChangeHistory' : ActorMethod<[string], Array<ChangeEvent>>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMembershipDetails' : ActorMethod<[MemberId], Membership>,
  'getMembershipProfile' : ActorMethod<[MemberId], MembershipProfile>,
  'getMembershipProfilesByStatus' : ActorMethod<[T], Array<MembershipProfile>>,
  'getPublishingWork' : ActorMethod<[PublishingId], PublishingWork>,
  'getRecordingProject' : ActorMethod<[RecodingId], RecordingProject>,
  'getRelease' : ActorMethod<[LabelEntityId], Release>,
  'getRemainingRolloutSteps' : ActorMethod<[], Array<[string, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateArtistDevelopment' : ActorMethod<
    [ArtistDevelopmentId, CreateArtistDevelopmentRequest],
    ArtistDevelopment
  >,
  'updateKnownUserRole' : ActorMethod<[], undefined>,
  'updateMembership' : ActorMethod<
    [MemberId, string, string, T],
    MembershipProfile
  >,
  'updateMembershipLinks' : ActorMethod<
    [
      MemberId,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'updateMembershipProfileFields' : ActorMethod<
    [MemberId, string, string],
    MembershipProfile
  >,
  'updateMembershipStatus' : ActorMethod<[MemberId, T], MembershipProfile>,
  'updatePublishingWork' : ActorMethod<
    [PublishingId, CreatePublishingWorkRequest],
    PublishingWork
  >,
  'updateRecordingProject' : ActorMethod<
    [RecodingId, CreateRecordingProjectRequest],
    RecordingProject
  >,
  'updateRelease' : ActorMethod<[LabelEntityId, CreateReleaseRequest], Release>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];