/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ArtistDevelopment {
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : Array<RecodingId>,
  'owner' : Principal,
  'relatedLabelEntities' : Array<LabelEntityId>,
  'artistId' : string,
  'created_at' : Time,
  'relatedArtistDevelopment' : Array<ArtistDevelopmentId>,
  'relatedMemberships' : Array<MemberId>,
  'goals' : Array<string>,
  'plans' : Array<string>,
  'internalNotes' : string,
  'relatedPublishing' : Array<PublishingId>,
  'milestones' : Array<string>,
}
export type ArtistDevelopmentId = string;
export interface ByGoals {
  'id' : ArtistDevelopmentId,
  'artistId' : string,
  'created_at' : Time,
  'goals' : string,
}
export type LabelEntityId = string;
export type MemberId = string;
export interface Membership {
  'linkedProjects' : Array<RecodingId>,
  'tier' : MembershipTier,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'profile' : MembershipProfile,
}
export interface MembershipProfile {
  'id' : MemberId,
  'agreements' : Array<string>,
  'status' : T,
  'updated_at' : Time,
  'principal' : Principal,
  'name' : string,
  'tier' : string,
  'created_at' : Time,
  'email' : string,
  'notes' : string,
}
export interface MembershipTier {
  'fee' : bigint,
  'name' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export type ProjectStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'archived' : null };
export type PublishingId = string;
export interface PublishingWork {
  'id' : PublishingId,
  'title' : string,
  'ownershipSplits' : Array<[string, bigint]>,
  'linkedProjects' : Array<RecodingId>,
  'owner' : Principal,
  'isrc' : [] | [string],
  'iswc' : [] | [string],
  'created_at' : Time,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'registrationStatus' : string,
  'contributors' : Array<string>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export type RecodingId = string;
export interface RecordingProject {
  'id' : RecodingId,
  'status' : ProjectStatus,
  'title' : string,
  'participants' : Array<string>,
  'sessionDate' : Time,
  'owner' : Principal,
  'created_at' : Time,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'assetReferences' : Array<string>,
  'linkedMembers' : Array<MemberId>,
  'notes' : string,
  'linkedArtists' : Array<ArtistDevelopmentId>,
}
export interface Release {
  'id' : LabelEntityId,
  'title' : string,
  'workflowChecklist' : Array<string>,
  'keyDates' : Array<string>,
  'owners' : Array<string>,
  'linkedProjects' : Array<RecodingId>,
  'owner' : Principal,
  'tracklist' : Array<string>,
  'created_at' : Time,
  'linkedWorks' : Array<PublishingId>,
  'linkedMembers' : Array<MemberId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'releaseType' : string,
}
export type T = { 'applicant' : null } |
  { 'active' : null } |
  { 'inactive' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPublishingWorkNotes' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignReleaseOwners' : ActorMethod<
    [LabelEntityId, Array<string>],
    undefined
  >,
  'createArtistDevelopment' : ActorMethod<
    [string, Array<string>, Array<string>, Array<string>, string],
    ArtistDevelopment
  >,
  'createMembershipProfile' : ActorMethod<
    [MemberId, string, string],
    MembershipProfile
  >,
  'createPublishingWork' : ActorMethod<
    [
      string,
      Array<string>,
      Array<[string, bigint]>,
      [] | [string],
      [] | [string],
      string,
    ],
    PublishingWork
  >,
  'createRecordingProject' : ActorMethod<
    [string, Array<string>, Time, ProjectStatus, string],
    RecordingProject
  >,
  'createRelease' : ActorMethod<
    [string, string, Array<string>, Array<string>, Array<string>],
    Release
  >,
  'getAllArtistDevelopment' : ActorMethod<[], Array<ArtistDevelopment>>,
  'getAllMembershipProfiles' : ActorMethod<[], Array<MembershipProfile>>,
  'getAllPublishingWorks' : ActorMethod<[], Array<PublishingWork>>,
  'getAllRecordingProjects' : ActorMethod<[], Array<RecordingProject>>,
  'getAllReleases' : ActorMethod<[], Array<Release>>,
  'getArtistDevelopment' : ActorMethod<
    [ArtistDevelopmentId],
    ArtistDevelopment
  >,
  'getArtistDevelopmentByGoals' : ActorMethod<[], Array<ByGoals>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntitiesForCaller' : ActorMethod<
    [],
    {
      'recordingProjects' : Array<RecordingProject>,
      'artistDevelopment' : Array<ArtistDevelopment>,
      'publishingWorks' : Array<PublishingWork>,
      'releases' : Array<Release>,
      'memberships' : Array<[MemberId, Membership]>,
    }
  >,
  'getMembershipDetails' : ActorMethod<[MemberId], Membership>,
  'getMembershipProfile' : ActorMethod<[MemberId], MembershipProfile>,
  'getMembershipProfilesByStatus' : ActorMethod<[T], Array<MembershipProfile>>,
  'getPublishingWork' : ActorMethod<[string], PublishingWork>,
  'getRecordingProject' : ActorMethod<[RecodingId], RecordingProject>,
  'getRelease' : ActorMethod<[LabelEntityId], Release>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'linkMembershipToEntities' : ActorMethod<
    [
      MemberId,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'linkProjectToEntities' : ActorMethod<
    [
      RecodingId,
      Array<MemberId>,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
    ],
    undefined
  >,
  'linkPublishingWorkToEntities' : ActorMethod<
    [
      PublishingId,
      Array<MemberId>,
      Array<ArtistDevelopmentId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'linkReleaseToEntities' : ActorMethod<
    [
      LabelEntityId,
      Array<MemberId>,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateArtistDevelopmentLinks' : ActorMethod<
    [
      ArtistDevelopmentId,
      Array<MemberId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
      Array<ArtistDevelopmentId>,
    ],
    undefined
  >,
  'updateMembershipLinks' : ActorMethod<
    [
      MemberId,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'updateMembershipProfile' : ActorMethod<
    [MemberId, string, string, T],
    MembershipProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];