/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LabelEntityId = IDL.Text;
export const ArtistDevelopmentId = IDL.Text;
export const RecodingId = IDL.Text;
export const Time = IDL.Int;
export const MemberId = IDL.Text;
export const PublishingId = IDL.Text;
export const ArtistDevelopment = IDL.Record({
  'id' : ArtistDevelopmentId,
  'relatedRecordingProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'relatedLabelEntities' : IDL.Vec(LabelEntityId),
  'artistId' : IDL.Text,
  'created_at' : Time,
  'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
  'relatedMemberships' : IDL.Vec(MemberId),
  'goals' : IDL.Vec(IDL.Text),
  'plans' : IDL.Vec(IDL.Text),
  'internalNotes' : IDL.Text,
  'relatedPublishing' : IDL.Vec(PublishingId),
  'milestones' : IDL.Vec(IDL.Text),
});
export const T = IDL.Variant({
  'applicant' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'paused' : IDL.Null,
});
export const MembershipProfile = IDL.Record({
  'id' : MemberId,
  'agreements' : IDL.Vec(IDL.Text),
  'status' : T,
  'updated_at' : Time,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'created_at' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
});
export const PublishingWork = IDL.Record({
  'id' : PublishingId,
  'title' : IDL.Text,
  'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'linkedProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'isrc' : IDL.Opt(IDL.Text),
  'iswc' : IDL.Opt(IDL.Text),
  'created_at' : Time,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'contributors' : IDL.Vec(IDL.Text),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const ProjectStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'archived' : IDL.Null,
});
export const RecordingProject = IDL.Record({
  'id' : RecodingId,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'sessionDate' : Time,
  'owner' : IDL.Principal,
  'created_at' : Time,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'assetReferences' : IDL.Vec(IDL.Text),
  'linkedMembers' : IDL.Vec(MemberId),
  'notes' : IDL.Text,
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
});
export const Release = IDL.Record({
  'id' : LabelEntityId,
  'title' : IDL.Text,
  'workflowChecklist' : IDL.Vec(IDL.Text),
  'keyDates' : IDL.Vec(IDL.Text),
  'owners' : IDL.Vec(IDL.Text),
  'linkedProjects' : IDL.Vec(RecodingId),
  'owner' : IDL.Principal,
  'tracklist' : IDL.Vec(IDL.Text),
  'created_at' : Time,
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedMembers' : IDL.Vec(MemberId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'releaseType' : IDL.Text,
});
export const ByGoals = IDL.Record({
  'id' : ArtistDevelopmentId,
  'artistId' : IDL.Text,
  'created_at' : Time,
  'goals' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const MembershipTier = IDL.Record({
  'fee' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const Membership = IDL.Record({
  'linkedProjects' : IDL.Vec(RecodingId),
  'tier' : MembershipTier,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'profile' : MembershipProfile,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPublishingWorkNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignReleaseOwners' : IDL.Func([LabelEntityId, IDL.Vec(IDL.Text)], [], []),
  'createArtistDevelopment' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [ArtistDevelopment],
      [],
    ),
  'createMembershipProfile' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text],
      [MembershipProfile],
      [],
    ),
  'createPublishingWork' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [PublishingWork],
      [],
    ),
  'createRecordingProject' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), Time, ProjectStatus, IDL.Text],
      [RecordingProject],
      [],
    ),
  'createRelease' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [Release],
      [],
    ),
  'getAllArtistDevelopment' : IDL.Func(
      [],
      [IDL.Vec(ArtistDevelopment)],
      ['query'],
    ),
  'getAllMembershipProfiles' : IDL.Func(
      [],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getAllPublishingWorks' : IDL.Func([], [IDL.Vec(PublishingWork)], ['query']),
  'getAllRecordingProjects' : IDL.Func(
      [],
      [IDL.Vec(RecordingProject)],
      ['query'],
    ),
  'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getArtistDevelopment' : IDL.Func(
      [ArtistDevelopmentId],
      [ArtistDevelopment],
      ['query'],
    ),
  'getArtistDevelopmentByGoals' : IDL.Func([], [IDL.Vec(ByGoals)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntitiesForCaller' : IDL.Func(
      [],
      [
        IDL.Record({
          'recordingProjects' : IDL.Vec(RecordingProject),
          'artistDevelopment' : IDL.Vec(ArtistDevelopment),
          'publishingWorks' : IDL.Vec(PublishingWork),
          'releases' : IDL.Vec(Release),
          'memberships' : IDL.Vec(IDL.Tuple(MemberId, Membership)),
        }),
      ],
      ['query'],
    ),
  'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
  'getMembershipProfile' : IDL.Func([MemberId], [MembershipProfile], ['query']),
  'getMembershipProfilesByStatus' : IDL.Func(
      [T],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getPublishingWork' : IDL.Func([IDL.Text], [PublishingWork], ['query']),
  'getRecordingProject' : IDL.Func([RecodingId], [RecordingProject], ['query']),
  'getRelease' : IDL.Func([LabelEntityId], [Release], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'linkMembershipToEntities' : IDL.Func(
      [
        MemberId,
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'linkProjectToEntities' : IDL.Func(
      [
        RecodingId,
        IDL.Vec(MemberId),
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
      ],
      [],
      [],
    ),
  'linkPublishingWorkToEntities' : IDL.Func(
      [
        PublishingId,
        IDL.Vec(MemberId),
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'linkReleaseToEntities' : IDL.Func(
      [
        LabelEntityId,
        IDL.Vec(MemberId),
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateArtistDevelopmentLinks' : IDL.Func(
      [
        ArtistDevelopmentId,
        IDL.Vec(MemberId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
        IDL.Vec(ArtistDevelopmentId),
      ],
      [],
      [],
    ),
  'updateMembershipLinks' : IDL.Func(
      [
        MemberId,
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'updateMembershipProfile' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text, T],
      [MembershipProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LabelEntityId = IDL.Text;
  const ArtistDevelopmentId = IDL.Text;
  const RecodingId = IDL.Text;
  const Time = IDL.Int;
  const MemberId = IDL.Text;
  const PublishingId = IDL.Text;
  const ArtistDevelopment = IDL.Record({
    'id' : ArtistDevelopmentId,
    'relatedRecordingProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'relatedLabelEntities' : IDL.Vec(LabelEntityId),
    'artistId' : IDL.Text,
    'created_at' : Time,
    'relatedArtistDevelopment' : IDL.Vec(ArtistDevelopmentId),
    'relatedMemberships' : IDL.Vec(MemberId),
    'goals' : IDL.Vec(IDL.Text),
    'plans' : IDL.Vec(IDL.Text),
    'internalNotes' : IDL.Text,
    'relatedPublishing' : IDL.Vec(PublishingId),
    'milestones' : IDL.Vec(IDL.Text),
  });
  const T = IDL.Variant({
    'applicant' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'paused' : IDL.Null,
  });
  const MembershipProfile = IDL.Record({
    'id' : MemberId,
    'agreements' : IDL.Vec(IDL.Text),
    'status' : T,
    'updated_at' : Time,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'created_at' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
  });
  const PublishingWork = IDL.Record({
    'id' : PublishingId,
    'title' : IDL.Text,
    'ownershipSplits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'linkedProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'isrc' : IDL.Opt(IDL.Text),
    'iswc' : IDL.Opt(IDL.Text),
    'created_at' : Time,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'contributors' : IDL.Vec(IDL.Text),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const ProjectStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'archived' : IDL.Null,
  });
  const RecordingProject = IDL.Record({
    'id' : RecodingId,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'sessionDate' : Time,
    'owner' : IDL.Principal,
    'created_at' : Time,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'assetReferences' : IDL.Vec(IDL.Text),
    'linkedMembers' : IDL.Vec(MemberId),
    'notes' : IDL.Text,
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  });
  const Release = IDL.Record({
    'id' : LabelEntityId,
    'title' : IDL.Text,
    'workflowChecklist' : IDL.Vec(IDL.Text),
    'keyDates' : IDL.Vec(IDL.Text),
    'owners' : IDL.Vec(IDL.Text),
    'linkedProjects' : IDL.Vec(RecodingId),
    'owner' : IDL.Principal,
    'tracklist' : IDL.Vec(IDL.Text),
    'created_at' : Time,
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedMembers' : IDL.Vec(MemberId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'releaseType' : IDL.Text,
  });
  const ByGoals = IDL.Record({
    'id' : ArtistDevelopmentId,
    'artistId' : IDL.Text,
    'created_at' : Time,
    'goals' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const MembershipTier = IDL.Record({
    'fee' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const Membership = IDL.Record({
    'linkedProjects' : IDL.Vec(RecodingId),
    'tier' : MembershipTier,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'profile' : MembershipProfile,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPublishingWorkNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignReleaseOwners' : IDL.Func(
        [LabelEntityId, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createArtistDevelopment' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [ArtistDevelopment],
        [],
      ),
    'createMembershipProfile' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text],
        [MembershipProfile],
        [],
      ),
    'createPublishingWork' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [PublishingWork],
        [],
      ),
    'createRecordingProject' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), Time, ProjectStatus, IDL.Text],
        [RecordingProject],
        [],
      ),
    'createRelease' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [Release],
        [],
      ),
    'getAllArtistDevelopment' : IDL.Func(
        [],
        [IDL.Vec(ArtistDevelopment)],
        ['query'],
      ),
    'getAllMembershipProfiles' : IDL.Func(
        [],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getAllPublishingWorks' : IDL.Func(
        [],
        [IDL.Vec(PublishingWork)],
        ['query'],
      ),
    'getAllRecordingProjects' : IDL.Func(
        [],
        [IDL.Vec(RecordingProject)],
        ['query'],
      ),
    'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getArtistDevelopment' : IDL.Func(
        [ArtistDevelopmentId],
        [ArtistDevelopment],
        ['query'],
      ),
    'getArtistDevelopmentByGoals' : IDL.Func([], [IDL.Vec(ByGoals)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntitiesForCaller' : IDL.Func(
        [],
        [
          IDL.Record({
            'recordingProjects' : IDL.Vec(RecordingProject),
            'artistDevelopment' : IDL.Vec(ArtistDevelopment),
            'publishingWorks' : IDL.Vec(PublishingWork),
            'releases' : IDL.Vec(Release),
            'memberships' : IDL.Vec(IDL.Tuple(MemberId, Membership)),
          }),
        ],
        ['query'],
      ),
    'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
    'getMembershipProfile' : IDL.Func(
        [MemberId],
        [MembershipProfile],
        ['query'],
      ),
    'getMembershipProfilesByStatus' : IDL.Func(
        [T],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getPublishingWork' : IDL.Func([IDL.Text], [PublishingWork], ['query']),
    'getRecordingProject' : IDL.Func(
        [RecodingId],
        [RecordingProject],
        ['query'],
      ),
    'getRelease' : IDL.Func([LabelEntityId], [Release], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'linkMembershipToEntities' : IDL.Func(
        [
          MemberId,
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'linkProjectToEntities' : IDL.Func(
        [
          RecodingId,
          IDL.Vec(MemberId),
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
        ],
        [],
        [],
      ),
    'linkPublishingWorkToEntities' : IDL.Func(
        [
          PublishingId,
          IDL.Vec(MemberId),
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'linkReleaseToEntities' : IDL.Func(
        [
          LabelEntityId,
          IDL.Vec(MemberId),
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateArtistDevelopmentLinks' : IDL.Func(
        [
          ArtistDevelopmentId,
          IDL.Vec(MemberId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
          IDL.Vec(ArtistDevelopmentId),
        ],
        [],
        [],
      ),
    'updateMembershipLinks' : IDL.Func(
        [
          MemberId,
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'updateMembershipProfile' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text, T],
        [MembershipProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };