/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PublishingId = string;
export type Time = bigint;
export type LabelEntityId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MemberId = string;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DashboardStats {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
}
export type RecodingId = string;
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type ArtistDevelopmentId = string;
export interface SignedInUser {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
}
export interface ChangeEvent {
    id: bigint;
    operationType: Variant_link_create_update;
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
}
export interface MembershipTier {
    fee: bigint;
    name: string;
    description: string;
    benefits: Array<string>;
}
export interface MembershipProfile {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
}
export interface Membership {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
}
export interface UserProfile {
    bio: string;
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ProjectStatus {
    in_progress = "in_progress",
    completed = "completed",
    planned = "planned",
    archived = "archived"
}
export enum T {
    applicant = "applicant",
    active = "active",
    inactive = "inactive",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_link_create_update {
    link = "link",
    create = "create",
    update = "update"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteMembershipProfiles(ids: Array<MemberId>): Promise<{
        deleted: Array<MemberId>;
        failed: Array<MemberId>;
    }>;
    createMembershipProfile(id: MemberId, name: string, email: string): Promise<MembershipProfile>;
    duplicateMembership(id: MemberId): Promise<Membership>;
    getAllKnownUsers(): Promise<Array<SignedInUser>>;
    getAllMembershipProfiles(): Promise<Array<MembershipProfile>>;
    getCallerMemberships(): Promise<Array<Membership>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChangeHistory(recordId: string): Promise<Array<ChangeEvent>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMembershipDetails(id: MemberId): Promise<Membership>;
    getMembershipProfile(id: MemberId): Promise<MembershipProfile>;
    getMembershipProfilesByStatus(status: T): Promise<Array<MembershipProfile>>;
    getRemainingRolloutSteps(): Promise<Array<[string, string]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateKnownUserRole(): Promise<void>;
    updateMembership(id: MemberId, name: string, email: string, status: T): Promise<MembershipProfile>;
    updateMembershipLinks(id: MemberId, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, releaseIds: Array<LabelEntityId>, projectIds: Array<RecodingId>): Promise<void>;
    updateMembershipProfileFields(id: MemberId, name: string, email: string): Promise<MembershipProfile>;
    updateMembershipStatus(id: MemberId, status: T): Promise<MembershipProfile>;
}
import type { ApprovalStatus as _ApprovalStatus, ArtistDevelopmentId as _ArtistDevelopmentId, ChangeEvent as _ChangeEvent, DashboardStats as _DashboardStats, LabelEntityId as _LabelEntityId, MemberId as _MemberId, Membership as _Membership, MembershipProfile as _MembershipProfile, MembershipTier as _MembershipTier, ProjectStatus as _ProjectStatus, PublishingId as _PublishingId, RecodingId as _RecodingId, SignedInUser as _SignedInUser, T as _T, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkDeleteMembershipProfiles(arg0: Array<MemberId>): Promise<{
        deleted: Array<MemberId>;
        failed: Array<MemberId>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteMembershipProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteMembershipProfiles(arg0);
            return result;
        }
    }
    async createMembershipProfile(arg0: MemberId, arg1: string, arg2: string): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicateMembership(arg0: MemberId): Promise<Membership> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateMembership(arg0);
                return from_candid_Membership_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateMembership(arg0);
            return from_candid_Membership_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKnownUsers(): Promise<Array<SignedInUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnownUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnownUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipProfiles(): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerMemberships(): Promise<Array<Membership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMemberships();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMemberships();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangeHistory(arg0: string): Promise<Array<ChangeEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeHistory(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeHistory(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipDetails(arg0: MemberId): Promise<Membership> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipDetails(arg0);
                return from_candid_Membership_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipDetails(arg0);
            return from_candid_Membership_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfile(arg0: MemberId): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfile(arg0);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfile(arg0);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfilesByStatus(arg0: T): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemainingRolloutSteps(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingRolloutSteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingRolloutSteps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateKnownUserRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKnownUserRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKnownUserRole();
            return result;
        }
    }
    async updateMembership(arg0: MemberId, arg1: string, arg2: string, arg3: T): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembership(arg0, arg1, arg2, to_candid_T_n36(this._uploadFile, this._downloadFile, arg3));
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembership(arg0, arg1, arg2, to_candid_T_n36(this._uploadFile, this._downloadFile, arg3));
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMembershipLinks(arg0: MemberId, arg1: Array<ArtistDevelopmentId>, arg2: Array<PublishingId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMembershipProfileFields(arg0: MemberId, arg1: string, arg2: string): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipProfileFields(arg0, arg1, arg2);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipProfileFields(arg0, arg1, arg2);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMembershipStatus(arg0: MemberId, arg1: T): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipStatus(arg0, to_candid_T_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipStatus(arg0, to_candid_T_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ChangeEvent_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangeEvent): ChangeEvent {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipProfile): MembershipProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Membership_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Membership): Membership {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SignedInUser_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignedInUser): SignedInUser {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_T_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    agreements: Array<string>;
    status: _T;
    updated_at: _Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: _Time;
    email: string;
    notes: string;
}): {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
} {
    return {
        id: value.id,
        agreements: value.agreements,
        status: from_candid_T_n12(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        principal: value.principal,
        name: value.name,
        tier: value.tier,
        created_at: value.created_at,
        email: value.email,
        notes: value.notes
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedProjects: Array<_RecodingId>;
    tier: _MembershipTier;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    linkedArtists: Array<_ArtistDevelopmentId>;
    profile: _MembershipProfile;
}): {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
} {
    return {
        linkedProjects: value.linkedProjects,
        tier: value.tier,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        linkedArtists: value.linkedArtists,
        profile: from_candid_MembershipProfile_n10(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n19(_uploadFile, _downloadFile, value.role),
        profile: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    operationType: {
        link: null;
    } | {
        create: null;
    } | {
        update: null;
    };
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
}): {
    id: bigint;
    operationType: Variant_link_create_update;
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
} {
    return {
        id: value.id,
        operationType: from_candid_variant_n27(_uploadFile, _downloadFile, value.operationType),
        author: value.author,
        changedFields: value.changedFields,
        timestamp: value.timestamp,
        recordId: value.recordId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[_T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[_ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
}): {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
} {
    return {
        totalMemberships: value.totalMemberships,
        membershipStatusCounts: from_candid_vec_n30(_uploadFile, _downloadFile, value.membershipStatusCounts),
        totalRecordingProjects: value.totalRecordingProjects,
        projectStatusCounts: from_candid_vec_n32(_uploadFile, _downloadFile, value.projectStatusCounts),
        totalPublishingWorks: value.totalPublishingWorks,
        totalArtistDevelopment: value.totalArtistDevelopment,
        releaseTypeCounts: value.releaseTypeCounts,
        totalReleases: value.totalReleases
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n41(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_T, bigint]): [T, bigint] {
    return [
        from_candid_T_n12(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProjectStatus, bigint]): [ProjectStatus, bigint] {
    return [
        from_candid_ProjectStatus_n34(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
}): T {
    return "applicant" in value ? T.applicant : "active" in value ? T.active : "inactive" in value ? T.inactive : "paused" in value ? T.paused : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    link: null;
} | {
    create: null;
} | {
    update: null;
}): Variant_link_create_update {
    return "link" in value ? Variant_link_create_update.link : "create" in value ? Variant_link_create_update.create : "update" in value ? Variant_link_create_update.update : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    archived: null;
}): ProjectStatus {
    return "in_progress" in value ? ProjectStatus.in_progress : "completed" in value ? ProjectStatus.completed : "planned" in value ? ProjectStatus.planned : "archived" in value ? ProjectStatus.archived : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignedInUser>): Array<SignedInUser> {
    return value.map((x)=>from_candid_SignedInUser_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipProfile>): Array<MembershipProfile> {
    return value.map((x)=>from_candid_MembershipProfile_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Membership>): Array<Membership> {
    return value.map((x)=>from_candid_Membership_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChangeEvent>): Array<ChangeEvent> {
    return value.map((x)=>from_candid_ChangeEvent_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_T, bigint]>): Array<[T, bigint]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProjectStatus, bigint]>): Array<[ProjectStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n39(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_T_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
} {
    return value == T.applicant ? {
        applicant: null
    } : value == T.active ? {
        active: null
    } : value == T.inactive ? {
        inactive: null
    } : value == T.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
