/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberId = IDL.Text;
export const T = IDL.Variant({
  'applicant' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'paused' : IDL.Null,
});
export const Time = IDL.Int;
export const MembershipProfile = IDL.Record({
  'id' : MemberId,
  'agreements' : IDL.Vec(IDL.Text),
  'status' : T,
  'updated_at' : Time,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'created_at' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
});
export const RecodingId = IDL.Text;
export const MembershipTier = IDL.Record({
  'fee' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const LabelEntityId = IDL.Text;
export const PublishingId = IDL.Text;
export const ArtistDevelopmentId = IDL.Text;
export const Membership = IDL.Record({
  'linkedProjects' : IDL.Vec(RecodingId),
  'tier' : MembershipTier,
  'linkedReleases' : IDL.Vec(LabelEntityId),
  'linkedWorks' : IDL.Vec(PublishingId),
  'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
  'profile' : MembershipProfile,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SignedInUser = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const ChangeEvent = IDL.Record({
  'id' : IDL.Nat,
  'operationType' : IDL.Variant({
    'link' : IDL.Null,
    'create' : IDL.Null,
    'update' : IDL.Null,
  }),
  'author' : IDL.Principal,
  'changedFields' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'recordId' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'archived' : IDL.Null,
});
export const DashboardStats = IDL.Record({
  'totalMemberships' : IDL.Nat,
  'membershipStatusCounts' : IDL.Vec(IDL.Tuple(T, IDL.Nat)),
  'totalRecordingProjects' : IDL.Nat,
  'projectStatusCounts' : IDL.Vec(IDL.Tuple(ProjectStatus, IDL.Nat)),
  'totalPublishingWorks' : IDL.Nat,
  'totalArtistDevelopment' : IDL.Nat,
  'releaseTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalReleases' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeleteMembershipProfiles' : IDL.Func(
      [IDL.Vec(MemberId)],
      [
        IDL.Record({
          'deleted' : IDL.Vec(MemberId),
          'failed' : IDL.Vec(MemberId),
        }),
      ],
      [],
    ),
  'createMembershipProfile' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text],
      [MembershipProfile],
      [],
    ),
  'duplicateMembership' : IDL.Func([MemberId], [Membership], []),
  'getAllKnownUsers' : IDL.Func([], [IDL.Vec(SignedInUser)], ['query']),
  'getAllMembershipProfiles' : IDL.Func(
      [],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getCallerMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangeHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChangeEvent)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
  'getMembershipProfile' : IDL.Func([MemberId], [MembershipProfile], ['query']),
  'getMembershipProfilesByStatus' : IDL.Func(
      [T],
      [IDL.Vec(MembershipProfile)],
      ['query'],
    ),
  'getRemainingRolloutSteps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateKnownUserRole' : IDL.Func([], [], []),
  'updateMembership' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text, T],
      [MembershipProfile],
      [],
    ),
  'updateMembershipLinks' : IDL.Func(
      [
        MemberId,
        IDL.Vec(ArtistDevelopmentId),
        IDL.Vec(PublishingId),
        IDL.Vec(LabelEntityId),
        IDL.Vec(RecodingId),
      ],
      [],
      [],
    ),
  'updateMembershipProfileFields' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text],
      [MembershipProfile],
      [],
    ),
  'updateMembershipStatus' : IDL.Func([MemberId, T], [MembershipProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberId = IDL.Text;
  const T = IDL.Variant({
    'applicant' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Time = IDL.Int;
  const MembershipProfile = IDL.Record({
    'id' : MemberId,
    'agreements' : IDL.Vec(IDL.Text),
    'status' : T,
    'updated_at' : Time,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'created_at' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
  });
  const RecodingId = IDL.Text;
  const MembershipTier = IDL.Record({
    'fee' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const LabelEntityId = IDL.Text;
  const PublishingId = IDL.Text;
  const ArtistDevelopmentId = IDL.Text;
  const Membership = IDL.Record({
    'linkedProjects' : IDL.Vec(RecodingId),
    'tier' : MembershipTier,
    'linkedReleases' : IDL.Vec(LabelEntityId),
    'linkedWorks' : IDL.Vec(PublishingId),
    'linkedArtists' : IDL.Vec(ArtistDevelopmentId),
    'profile' : MembershipProfile,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const SignedInUser = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const ChangeEvent = IDL.Record({
    'id' : IDL.Nat,
    'operationType' : IDL.Variant({
      'link' : IDL.Null,
      'create' : IDL.Null,
      'update' : IDL.Null,
    }),
    'author' : IDL.Principal,
    'changedFields' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'recordId' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'archived' : IDL.Null,
  });
  const DashboardStats = IDL.Record({
    'totalMemberships' : IDL.Nat,
    'membershipStatusCounts' : IDL.Vec(IDL.Tuple(T, IDL.Nat)),
    'totalRecordingProjects' : IDL.Nat,
    'projectStatusCounts' : IDL.Vec(IDL.Tuple(ProjectStatus, IDL.Nat)),
    'totalPublishingWorks' : IDL.Nat,
    'totalArtistDevelopment' : IDL.Nat,
    'releaseTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalReleases' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeleteMembershipProfiles' : IDL.Func(
        [IDL.Vec(MemberId)],
        [
          IDL.Record({
            'deleted' : IDL.Vec(MemberId),
            'failed' : IDL.Vec(MemberId),
          }),
        ],
        [],
      ),
    'createMembershipProfile' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text],
        [MembershipProfile],
        [],
      ),
    'duplicateMembership' : IDL.Func([MemberId], [Membership], []),
    'getAllKnownUsers' : IDL.Func([], [IDL.Vec(SignedInUser)], ['query']),
    'getAllMembershipProfiles' : IDL.Func(
        [],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getCallerMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangeHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChangeEvent)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMembershipDetails' : IDL.Func([MemberId], [Membership], ['query']),
    'getMembershipProfile' : IDL.Func(
        [MemberId],
        [MembershipProfile],
        ['query'],
      ),
    'getMembershipProfilesByStatus' : IDL.Func(
        [T],
        [IDL.Vec(MembershipProfile)],
        ['query'],
      ),
    'getRemainingRolloutSteps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateKnownUserRole' : IDL.Func([], [], []),
    'updateMembership' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text, T],
        [MembershipProfile],
        [],
      ),
    'updateMembershipLinks' : IDL.Func(
        [
          MemberId,
          IDL.Vec(ArtistDevelopmentId),
          IDL.Vec(PublishingId),
          IDL.Vec(LabelEntityId),
          IDL.Vec(RecodingId),
        ],
        [],
        [],
      ),
    'updateMembershipProfileFields' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text],
        [MembershipProfile],
        [],
      ),
    'updateMembershipStatus' : IDL.Func([MemberId, T], [MembershipProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };