/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ArtistDevelopmentId = string;
export interface ChangeEvent {
  'id' : bigint,
  'operationType' : { 'link' : null } |
    { 'create' : null } |
    { 'update' : null },
  'author' : Principal,
  'changedFields' : Array<string>,
  'timestamp' : bigint,
  'recordId' : string,
}
export interface DashboardStats {
  'totalMemberships' : bigint,
  'membershipStatusCounts' : Array<[T, bigint]>,
  'totalRecordingProjects' : bigint,
  'projectStatusCounts' : Array<[ProjectStatus, bigint]>,
  'totalPublishingWorks' : bigint,
  'totalArtistDevelopment' : bigint,
  'releaseTypeCounts' : Array<[string, bigint]>,
  'totalReleases' : bigint,
}
export type LabelEntityId = string;
export type MemberId = string;
export interface Membership {
  'linkedProjects' : Array<RecodingId>,
  'tier' : MembershipTier,
  'linkedReleases' : Array<LabelEntityId>,
  'linkedWorks' : Array<PublishingId>,
  'linkedArtists' : Array<ArtistDevelopmentId>,
  'profile' : MembershipProfile,
}
export interface MembershipProfile {
  'id' : MemberId,
  'agreements' : Array<string>,
  'status' : T,
  'updated_at' : Time,
  'principal' : Principal,
  'name' : string,
  'tier' : string,
  'created_at' : Time,
  'email' : string,
  'notes' : string,
}
export interface MembershipTier {
  'fee' : bigint,
  'name' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export type ProjectStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'archived' : null };
export type PublishingId = string;
export type RecodingId = string;
export interface SignedInUser {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export type T = { 'applicant' : null } |
  { 'active' : null } |
  { 'inactive' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteMembershipProfiles' : ActorMethod<
    [Array<MemberId>],
    { 'deleted' : Array<MemberId>, 'failed' : Array<MemberId> }
  >,
  'createMembershipProfile' : ActorMethod<
    [MemberId, string, string],
    MembershipProfile
  >,
  'duplicateMembership' : ActorMethod<[MemberId], Membership>,
  'getAllKnownUsers' : ActorMethod<[], Array<SignedInUser>>,
  'getAllMembershipProfiles' : ActorMethod<[], Array<MembershipProfile>>,
  'getCallerMemberships' : ActorMethod<[], Array<Membership>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChangeHistory' : ActorMethod<[string], Array<ChangeEvent>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMembershipDetails' : ActorMethod<[MemberId], Membership>,
  'getMembershipProfile' : ActorMethod<[MemberId], MembershipProfile>,
  'getMembershipProfilesByStatus' : ActorMethod<[T], Array<MembershipProfile>>,
  'getRemainingRolloutSteps' : ActorMethod<[], Array<[string, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateKnownUserRole' : ActorMethod<[], undefined>,
  'updateMembership' : ActorMethod<
    [MemberId, string, string, T],
    MembershipProfile
  >,
  'updateMembershipLinks' : ActorMethod<
    [
      MemberId,
      Array<ArtistDevelopmentId>,
      Array<PublishingId>,
      Array<LabelEntityId>,
      Array<RecodingId>,
    ],
    undefined
  >,
  'updateMembershipProfileFields' : ActorMethod<
    [MemberId, string, string],
    MembershipProfile
  >,
  'updateMembershipStatus' : ActorMethod<[MemberId, T], MembershipProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];