/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PublishingId = string;
export type Time = bigint;
export type LabelEntityId = string;
export type MemberId = string;
export interface ByGoals {
    id: ArtistDevelopmentId;
    artistId: string;
    created_at: Time;
    goals: string;
}
export interface ArtistDevelopment {
    id: ArtistDevelopmentId;
    relatedRecordingProjects: Array<RecodingId>;
    owner: Principal;
    relatedLabelEntities: Array<LabelEntityId>;
    artistId: string;
    created_at: Time;
    relatedArtistDevelopment: Array<ArtistDevelopmentId>;
    relatedMemberships: Array<MemberId>;
    goals: Array<string>;
    plans: Array<string>;
    internalNotes: string;
    relatedPublishing: Array<PublishingId>;
    milestones: Array<string>;
}
export type RecodingId = string;
export interface RecordingProject {
    id: RecodingId;
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    owner: Principal;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface PublishingWork {
    id: PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    isrc?: string;
    iswc?: string;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export interface Release {
    id: LabelEntityId;
    title: string;
    workflowChecklist: Array<string>;
    keyDates: Array<string>;
    owners: Array<string>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    tracklist: Array<string>;
    created_at: Time;
    linkedWorks: Array<PublishingId>;
    linkedMembers: Array<MemberId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    releaseType: string;
}
export type ArtistDevelopmentId = string;
export interface SignedInUser {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
}
export interface MembershipTier {
    fee: bigint;
    name: string;
    description: string;
    benefits: Array<string>;
}
export interface MembershipProfile {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
}
export interface Membership {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
}
export interface UserProfile {
    bio: string;
    name: string;
    email: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ProjectStatus {
    in_progress = "in_progress",
    completed = "completed",
    planned = "planned",
    archived = "archived"
}
export enum T {
    applicant = "applicant",
    active = "active",
    inactive = "inactive",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPublishingWorkNotes(id: string, notes: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignReleaseOwners(releaseId: LabelEntityId, owners: Array<string>): Promise<void>;
    createArtistDevelopment(artistId: string, goals: Array<string>, plans: Array<string>, milestones: Array<string>, internalNotes: string): Promise<ArtistDevelopment>;
    createMembershipProfile(id: MemberId, name: string, email: string): Promise<MembershipProfile>;
    createPublishingWork(title: string, contributors: Array<string>, ownershipSplits: Array<[string, bigint]>, iswc: string | null, isrc: string | null, registrationStatus: string): Promise<PublishingWork>;
    createRecordingProject(title: string, participants: Array<string>, sessionDate: Time, status: ProjectStatus, notes: string): Promise<RecordingProject>;
    createRelease(title: string, releaseType: string, tracklist: Array<string>, keyDates: Array<string>, owners: Array<string>): Promise<Release>;
    getAllArtistDevelopment(): Promise<Array<ArtistDevelopment>>;
    getAllKnownUsers(): Promise<Array<SignedInUser>>;
    getAllMembershipProfiles(): Promise<Array<MembershipProfile>>;
    getAllPublishingWorks(): Promise<Array<PublishingWork>>;
    getAllRecordingProjects(): Promise<Array<RecordingProject>>;
    getAllReleases(): Promise<Array<Release>>;
    getArtistDevelopment(entryId: ArtistDevelopmentId): Promise<ArtistDevelopment>;
    getArtistDevelopmentByGoals(): Promise<Array<ByGoals>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEntitiesForCaller(): Promise<{
        recordingProjects: Array<RecordingProject>;
        artistDevelopment: Array<ArtistDevelopment>;
        publishingWorks: Array<PublishingWork>;
        releases: Array<Release>;
        memberships: Array<[MemberId, Membership]>;
    }>;
    getMembershipDetails(id: MemberId): Promise<Membership>;
    getMembershipProfile(id: MemberId): Promise<MembershipProfile>;
    getMembershipProfilesByStatus(status: T): Promise<Array<MembershipProfile>>;
    getPublishingWork(id: string): Promise<PublishingWork>;
    getRecordingProject(projectId: RecodingId): Promise<RecordingProject>;
    getRelease(releaseId: LabelEntityId): Promise<Release>;
    getRemainingRolloutSteps(): Promise<Array<[string, string]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    linkMembershipToEntities(memberId: MemberId, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, releaseIds: Array<LabelEntityId>, projectIds: Array<RecodingId>): Promise<void>;
    linkProjectToEntities(projectId: RecodingId, memberIds: Array<MemberId>, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, releaseIds: Array<LabelEntityId>): Promise<void>;
    linkPublishingWorkToEntities(workId: PublishingId, memberIds: Array<MemberId>, artistIds: Array<ArtistDevelopmentId>, releaseIds: Array<LabelEntityId>, projectIds: Array<RecodingId>): Promise<void>;
    linkReleaseToEntities(releaseId: LabelEntityId, memberIds: Array<MemberId>, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, projectIds: Array<RecodingId>): Promise<void>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateArtistDevelopmentLinks(artistDevelopmentId: ArtistDevelopmentId, relatedMemberships: Array<MemberId>, relatedPublishing: Array<PublishingId>, relatedLabelEntities: Array<LabelEntityId>, relatedRecordingProjects: Array<RecodingId>, relatedArtistDevelopment: Array<ArtistDevelopmentId>): Promise<void>;
    updateKnownUserRole(): Promise<void>;
    updateMembershipLinks(id: MemberId, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, releaseIds: Array<LabelEntityId>, projectIds: Array<RecodingId>): Promise<void>;
    updateMembershipProfile(id: MemberId, name: string, email: string, status: T): Promise<MembershipProfile>;
}
import type { ApprovalStatus as _ApprovalStatus, ArtistDevelopment as _ArtistDevelopment, ArtistDevelopmentId as _ArtistDevelopmentId, LabelEntityId as _LabelEntityId, MemberId as _MemberId, Membership as _Membership, MembershipProfile as _MembershipProfile, MembershipTier as _MembershipTier, ProjectStatus as _ProjectStatus, PublishingId as _PublishingId, PublishingWork as _PublishingWork, RecodingId as _RecodingId, RecordingProject as _RecordingProject, Release as _Release, SignedInUser as _SignedInUser, T as _T, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPublishingWorkNotes(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublishingWorkNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublishingWorkNotes(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignReleaseOwners(arg0: LabelEntityId, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignReleaseOwners(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignReleaseOwners(arg0, arg1);
            return result;
        }
    }
    async createArtistDevelopment(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>, arg4: string): Promise<ArtistDevelopment> {
        if (this.processError) {
            try {
                const result = await this.actor.createArtistDevelopment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArtistDevelopment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMembershipProfile(arg0: MemberId, arg1: string, arg2: string): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
                return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
            return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPublishingWork(arg0: string, arg1: Array<string>, arg2: Array<[string, bigint]>, arg3: string | null, arg4: string | null, arg5: string): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublishingWork(arg0, arg1, arg2, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_PublishingWork_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublishingWork(arg0, arg1, arg2, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_PublishingWork_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecordingProject(arg0: string, arg1: Array<string>, arg2: Time, arg3: ProjectStatus, arg4: string): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecordingProject(arg0, arg1, arg2, to_candid_ProjectStatus_n11(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_RecordingProject_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecordingProject(arg0, arg1, arg2, to_candid_ProjectStatus_n11(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_RecordingProject_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRelease(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: Array<string>): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.createRelease(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRelease(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllArtistDevelopment(): Promise<Array<ArtistDevelopment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtistDevelopment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtistDevelopment();
            return result;
        }
    }
    async getAllKnownUsers(): Promise<Array<SignedInUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnownUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnownUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipProfiles(): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipProfiles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipProfiles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishingWorks(): Promise<Array<PublishingWork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishingWorks();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishingWorks();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecordingProjects(): Promise<Array<RecordingProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordingProjects();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordingProjects();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReleases(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReleases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReleases();
            return result;
        }
    }
    async getArtistDevelopment(arg0: ArtistDevelopmentId): Promise<ArtistDevelopment> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistDevelopment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistDevelopment(arg0);
            return result;
        }
    }
    async getArtistDevelopmentByGoals(): Promise<Array<ByGoals>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistDevelopmentByGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistDevelopmentByGoals();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntitiesForCaller(): Promise<{
        recordingProjects: Array<RecordingProject>;
        artistDevelopment: Array<ArtistDevelopment>;
        publishingWorks: Array<PublishingWork>;
        releases: Array<Release>;
        memberships: Array<[MemberId, Membership]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntitiesForCaller();
                return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntitiesForCaller();
            return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipDetails(arg0: MemberId): Promise<Membership> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipDetails(arg0);
                return from_candid_Membership_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipDetails(arg0);
            return from_candid_Membership_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfile(arg0: MemberId): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfile(arg0);
                return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfile(arg0);
            return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfilesByStatus(arg0: T): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishingWork(arg0: string): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishingWork(arg0);
                return from_candid_PublishingWork_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishingWork(arg0);
            return from_candid_PublishingWork_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordingProject(arg0: RecodingId): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordingProject(arg0);
                return from_candid_RecordingProject_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordingProject(arg0);
            return from_candid_RecordingProject_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelease(arg0: LabelEntityId): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelease(arg0);
            return result;
        }
    }
    async getRemainingRolloutSteps(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingRolloutSteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingRolloutSteps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async linkMembershipToEntities(arg0: MemberId, arg1: Array<ArtistDevelopmentId>, arg2: Array<PublishingId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkMembershipToEntities(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkMembershipToEntities(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async linkProjectToEntities(arg0: RecodingId, arg1: Array<MemberId>, arg2: Array<ArtistDevelopmentId>, arg3: Array<PublishingId>, arg4: Array<LabelEntityId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkProjectToEntities(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkProjectToEntities(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async linkPublishingWorkToEntities(arg0: PublishingId, arg1: Array<MemberId>, arg2: Array<ArtistDevelopmentId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkPublishingWorkToEntities(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkPublishingWorkToEntities(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async linkReleaseToEntities(arg0: LabelEntityId, arg1: Array<MemberId>, arg2: Array<ArtistDevelopmentId>, arg3: Array<PublishingId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkReleaseToEntities(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkReleaseToEntities(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateArtistDevelopmentLinks(arg0: ArtistDevelopmentId, arg1: Array<MemberId>, arg2: Array<PublishingId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>, arg5: Array<ArtistDevelopmentId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArtistDevelopmentLinks(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArtistDevelopmentLinks(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateKnownUserRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKnownUserRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKnownUserRole();
            return result;
        }
    }
    async updateMembershipLinks(arg0: MemberId, arg1: Array<ArtistDevelopmentId>, arg2: Array<PublishingId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMembershipProfile(arg0: MemberId, arg1: string, arg2: string, arg3: T): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipProfile(arg0, arg1, arg2, to_candid_T_n31(this._uploadFile, this._downloadFile, arg3));
                return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipProfile(arg0, arg1, arg2, to_candid_T_n31(this._uploadFile, this._downloadFile, arg3));
            return from_candid_MembershipProfile_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipProfile): MembershipProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Membership_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Membership): Membership {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PublishingWork_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishingWork): PublishingWork {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RecordingProject_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordingProject): RecordingProject {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SignedInUser_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignedInUser): SignedInUser {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_T_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecodingId;
    status: _ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: _Time;
    owner: Principal;
    created_at: _Time;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    linkedArtists: Array<_ArtistDevelopmentId>;
}): {
    id: RecodingId;
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    owner: Principal;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        participants: value.participants,
        sessionDate: value.sessionDate,
        owner: value.owner,
        created_at: value.created_at,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        assetReferences: value.assetReferences,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        linkedArtists: value.linkedArtists
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n20(_uploadFile, _downloadFile, value.role),
        profile: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recordingProjects: Array<_RecordingProject>;
    artistDevelopment: Array<_ArtistDevelopment>;
    publishingWorks: Array<_PublishingWork>;
    releases: Array<_Release>;
    memberships: Array<[_MemberId, _Membership]>;
}): {
    recordingProjects: Array<RecordingProject>;
    artistDevelopment: Array<ArtistDevelopment>;
    publishingWorks: Array<PublishingWork>;
    releases: Array<Release>;
    memberships: Array<[MemberId, Membership]>;
} {
    return {
        recordingProjects: from_candid_vec_n25(_uploadFile, _downloadFile, value.recordingProjects),
        artistDevelopment: value.artistDevelopment,
        publishingWorks: from_candid_vec_n24(_uploadFile, _downloadFile, value.publishingWorks),
        releases: value.releases,
        memberships: from_candid_vec_n27(_uploadFile, _downloadFile, value.memberships)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedProjects: Array<_RecodingId>;
    tier: _MembershipTier;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    linkedArtists: Array<_ArtistDevelopmentId>;
    profile: _MembershipProfile;
}): {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
} {
    return {
        linkedProjects: value.linkedProjects,
        tier: value.tier,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        linkedArtists: value.linkedArtists,
        profile: from_candid_MembershipProfile_n3(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    agreements: Array<string>;
    status: _T;
    updated_at: _Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: _Time;
    email: string;
    notes: string;
}): {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
} {
    return {
        id: value.id,
        agreements: value.agreements,
        status: from_candid_T_n5(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        principal: value.principal,
        name: value.name,
        tier: value.tier,
        created_at: value.created_at,
        email: value.email,
        notes: value.notes
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<_RecodingId>;
    owner: Principal;
    isrc: [] | [string];
    iswc: [] | [string];
    created_at: _Time;
    linkedReleases: Array<_LabelEntityId>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<_ArtistDevelopmentId>;
}): {
    id: PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    isrc?: string;
    iswc?: string;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
} {
    return {
        id: value.id,
        title: value.title,
        ownershipSplits: value.ownershipSplits,
        linkedProjects: value.linkedProjects,
        owner: value.owner,
        isrc: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.isrc)),
        iswc: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.iswc)),
        created_at: value.created_at,
        linkedReleases: value.linkedReleases,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        registrationStatus: value.registrationStatus,
        contributors: value.contributors,
        linkedArtists: value.linkedArtists
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MemberId, _Membership]): [MemberId, Membership] {
    return [
        value[0],
        from_candid_Membership_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    archived: null;
}): ProjectStatus {
    return "in_progress" in value ? ProjectStatus.in_progress : "completed" in value ? ProjectStatus.completed : "planned" in value ? ProjectStatus.planned : "archived" in value ? ProjectStatus.archived : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
}): T {
    return "applicant" in value ? T.applicant : "active" in value ? T.active : "inactive" in value ? T.inactive : "paused" in value ? T.paused : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignedInUser>): Array<SignedInUser> {
    return value.map((x)=>from_candid_SignedInUser_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipProfile>): Array<MembershipProfile> {
    return value.map((x)=>from_candid_MembershipProfile_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublishingWork>): Array<PublishingWork> {
    return value.map((x)=>from_candid_PublishingWork_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecordingProject>): Array<RecordingProject> {
    return value.map((x)=>from_candid_RecordingProject_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MemberId, _Membership]>): Array<[MemberId, Membership]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n34(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_T_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    in_progress: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    archived: null;
} {
    return value == ProjectStatus.in_progress ? {
        in_progress: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.planned ? {
        planned: null
    } : value == ProjectStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
} {
    return value == T.applicant ? {
        applicant: null
    } : value == T.active ? {
        active: null
    } : value == T.inactive ? {
        inactive: null
    } : value == T.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
