/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PublishingId = string;
export type Time = bigint;
export type LabelEntityId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ArtistDevelopment {
    id: ArtistDevelopmentId;
    relatedRecordingProjects: Array<RecodingId>;
    owner: Principal;
    relatedLabelEntities: Array<LabelEntityId>;
    artistId: string;
    created_at: Time;
    relatedArtistDevelopment: Array<ArtistDevelopmentId>;
    relatedMemberships: Array<MemberId>;
    goals: Array<string>;
    plans: Array<string>;
    internalNotes: string;
    relatedPublishing: Array<PublishingId>;
    milestones: Array<string>;
}
export interface RecordingProject {
    id: RecodingId;
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    owner: Principal;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export type ArtistDevelopmentId = string;
export interface PublishingWork {
    id: PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    isrc?: string;
    iswc?: string;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export interface Release {
    id: LabelEntityId;
    title: string;
    workflowChecklist: Array<string>;
    keyDates: Array<string>;
    owners: Array<string>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    tracklist: Array<string>;
    created_at: Time;
    linkedWorks: Array<PublishingId>;
    linkedMembers: Array<MemberId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    releaseType: string;
}
export interface CreatePublishingWorkRequest {
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    isrc?: string;
    iswc?: string;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export interface CreateArtistDevelopmentRequest {
    relatedRecordingProjects: Array<RecodingId>;
    relatedLabelEntities: Array<LabelEntityId>;
    artistId: string;
    relatedArtistDevelopment: Array<ArtistDevelopmentId>;
    relatedMemberships: Array<MemberId>;
    goals: Array<string>;
    plans: Array<string>;
    internalNotes: string;
    relatedPublishing: Array<PublishingId>;
    milestones: Array<string>;
}
export interface ChangeEvent {
    id: bigint;
    operationType: Variant_link_create_update;
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
}
export interface CreateRecordingProjectRequest {
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
}
export interface MembershipTier {
    fee: bigint;
    name: string;
    description: string;
    benefits: Array<string>;
}
export interface MembershipProfile {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
}
export interface Comment {
    id: bigint;
    createdAt: Time;
    text: string;
    author: Principal;
    recordId: string;
}
export type MemberId = string;
export interface DashboardStats {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
}
export type RecodingId = string;
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface CreateArtistDevelopmentResponse {
    id: ArtistDevelopmentId;
    relatedRecordingProjects: Array<RecodingId>;
    owner: Principal;
    relatedLabelEntities: Array<LabelEntityId>;
    artistId: string;
    created_at: Time;
    relatedArtistDevelopment: Array<ArtistDevelopmentId>;
    relatedMemberships: Array<MemberId>;
    goals: Array<string>;
    plans: Array<string>;
    internalNotes: string;
    relatedPublishing: Array<PublishingId>;
    milestones: Array<string>;
}
export interface SignedInUser {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
}
export interface CreateReleaseRequest {
    title: string;
    workflowChecklist: Array<string>;
    keyDates: Array<string>;
    owners: Array<string>;
    linkedProjects: Array<RecodingId>;
    tracklist: Array<string>;
    linkedWorks: Array<PublishingId>;
    linkedMembers: Array<MemberId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    releaseType: string;
}
export interface Membership {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
}
export interface UserProfile {
    bio: string;
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ProjectStatus {
    in_progress = "in_progress",
    completed = "completed",
    planned = "planned",
    archived = "archived"
}
export enum T {
    applicant = "applicant",
    active = "active",
    inactive = "inactive",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_link_create_update {
    link = "link",
    create = "create",
    update = "update"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(recordId: string, text: string): Promise<Comment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteMembershipProfiles(ids: Array<MemberId>): Promise<{
        deleted: Array<MemberId>;
        failed: Array<MemberId>;
    }>;
    createArtistDevelopment(request: CreateArtistDevelopmentRequest): Promise<CreateArtistDevelopmentResponse>;
    createMembershipProfile(id: MemberId, name: string, email: string): Promise<MembershipProfile>;
    createPublishingWork(request: CreatePublishingWorkRequest): Promise<PublishingWork>;
    createRecordingProject(request: CreateRecordingProjectRequest): Promise<RecordingProject>;
    createRelease(request: CreateReleaseRequest): Promise<Release>;
    deleteArtistDevelopment(id: ArtistDevelopmentId): Promise<void>;
    deleteComment(recordId: string, commentId: bigint): Promise<void>;
    deleteMembership(id: MemberId): Promise<void>;
    deletePublishingWork(id: PublishingId): Promise<void>;
    deleteRecordingProject(id: RecodingId): Promise<void>;
    deleteRelease(id: LabelEntityId): Promise<void>;
    duplicateArtistDevelopment(id: ArtistDevelopmentId): Promise<ArtistDevelopment>;
    duplicateMembership(id: MemberId): Promise<Membership>;
    duplicatePublishingWork(id: PublishingId): Promise<PublishingWork>;
    duplicateRecordingProject(id: RecodingId): Promise<RecordingProject>;
    duplicateRelease(id: LabelEntityId): Promise<Release>;
    getAllArtistDevelopments(): Promise<Array<ArtistDevelopment>>;
    getAllKnownUsers(): Promise<Array<SignedInUser>>;
    getAllMembershipProfiles(): Promise<Array<MembershipProfile>>;
    getAllPublishingWorks(): Promise<Array<PublishingWork>>;
    getAllRecordingProjects(): Promise<Array<RecordingProject>>;
    getAllReleases(): Promise<Array<Release>>;
    getArtistDevelopment(id: ArtistDevelopmentId): Promise<ArtistDevelopment>;
    getCallerArtistDevelopments(): Promise<Array<ArtistDevelopment>>;
    getCallerMemberships(): Promise<Array<Membership>>;
    getCallerPublishingWorks(): Promise<Array<PublishingWork>>;
    getCallerRecordingProjects(): Promise<Array<RecordingProject>>;
    getCallerReleases(): Promise<Array<Release>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChangeHistory(recordId: string): Promise<Array<ChangeEvent>>;
    getComments(recordId: string): Promise<Array<Comment>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMembershipDetails(id: MemberId): Promise<Membership>;
    getMembershipProfile(id: MemberId): Promise<MembershipProfile>;
    getMembershipProfilesByStatus(status: T): Promise<Array<MembershipProfile>>;
    getPublishingWork(id: PublishingId): Promise<PublishingWork>;
    getRecordingProject(id: RecodingId): Promise<RecordingProject>;
    getRelease(id: LabelEntityId): Promise<Release>;
    getRemainingRolloutSteps(): Promise<Array<[string, string]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateArtistDevelopment(id: ArtistDevelopmentId, request: CreateArtistDevelopmentRequest): Promise<ArtistDevelopment>;
    updateKnownUserRole(): Promise<void>;
    updateMembership(id: MemberId, name: string, email: string, status: T): Promise<MembershipProfile>;
    updateMembershipLinks(id: MemberId, artistIds: Array<ArtistDevelopmentId>, workIds: Array<PublishingId>, releaseIds: Array<LabelEntityId>, projectIds: Array<RecodingId>): Promise<void>;
    updateMembershipProfileFields(id: MemberId, name: string, email: string): Promise<MembershipProfile>;
    updateMembershipStatus(id: MemberId, status: T): Promise<MembershipProfile>;
    updatePublishingWork(id: PublishingId, request: CreatePublishingWorkRequest): Promise<PublishingWork>;
    updateRecordingProject(id: RecodingId, request: CreateRecordingProjectRequest): Promise<RecordingProject>;
    updateRelease(id: LabelEntityId, request: CreateReleaseRequest): Promise<Release>;
}
import type { ApprovalStatus as _ApprovalStatus, ArtistDevelopmentId as _ArtistDevelopmentId, ChangeEvent as _ChangeEvent, CreatePublishingWorkRequest as _CreatePublishingWorkRequest, CreateRecordingProjectRequest as _CreateRecordingProjectRequest, DashboardStats as _DashboardStats, LabelEntityId as _LabelEntityId, MemberId as _MemberId, Membership as _Membership, MembershipProfile as _MembershipProfile, MembershipTier as _MembershipTier, ProjectStatus as _ProjectStatus, PublishingId as _PublishingId, PublishingWork as _PublishingWork, RecodingId as _RecodingId, RecordingProject as _RecordingProject, SignedInUser as _SignedInUser, T as _T, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkDeleteMembershipProfiles(arg0: Array<MemberId>): Promise<{
        deleted: Array<MemberId>;
        failed: Array<MemberId>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteMembershipProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteMembershipProfiles(arg0);
            return result;
        }
    }
    async createArtistDevelopment(arg0: CreateArtistDevelopmentRequest): Promise<CreateArtistDevelopmentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createArtistDevelopment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArtistDevelopment(arg0);
            return result;
        }
    }
    async createMembershipProfile(arg0: MemberId, arg1: string, arg2: string): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipProfile(arg0, arg1, arg2);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPublishingWork(arg0: CreatePublishingWorkRequest): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublishingWork(to_candid_CreatePublishingWorkRequest_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublishingWork(to_candid_CreatePublishingWorkRequest_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecordingProject(arg0: CreateRecordingProjectRequest): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecordingProject(to_candid_CreateRecordingProjectRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecordingProject(to_candid_CreateRecordingProjectRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRelease(arg0: CreateReleaseRequest): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.createRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRelease(arg0);
            return result;
        }
    }
    async deleteArtistDevelopment(arg0: ArtistDevelopmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArtistDevelopment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArtistDevelopment(arg0);
            return result;
        }
    }
    async deleteComment(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deleteMembership(arg0: MemberId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembership(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembership(arg0);
            return result;
        }
    }
    async deletePublishingWork(arg0: PublishingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublishingWork(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublishingWork(arg0);
            return result;
        }
    }
    async deleteRecordingProject(arg0: RecodingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecordingProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecordingProject(arg0);
            return result;
        }
    }
    async deleteRelease(arg0: LabelEntityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRelease(arg0);
            return result;
        }
    }
    async duplicateArtistDevelopment(arg0: ArtistDevelopmentId): Promise<ArtistDevelopment> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateArtistDevelopment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateArtistDevelopment(arg0);
            return result;
        }
    }
    async duplicateMembership(arg0: MemberId): Promise<Membership> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateMembership(arg0);
                return from_candid_Membership_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateMembership(arg0);
            return from_candid_Membership_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicatePublishingWork(arg0: PublishingId): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicatePublishingWork(arg0);
                return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicatePublishingWork(arg0);
            return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicateRecordingProject(arg0: RecodingId): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateRecordingProject(arg0);
                return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateRecordingProject(arg0);
            return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicateRelease(arg0: LabelEntityId): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateRelease(arg0);
            return result;
        }
    }
    async getAllArtistDevelopments(): Promise<Array<ArtistDevelopment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtistDevelopments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtistDevelopments();
            return result;
        }
    }
    async getAllKnownUsers(): Promise<Array<SignedInUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnownUsers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnownUsers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipProfiles(): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipProfiles();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipProfiles();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishingWorks(): Promise<Array<PublishingWork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishingWorks();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishingWorks();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecordingProjects(): Promise<Array<RecordingProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordingProjects();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordingProjects();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReleases(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReleases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReleases();
            return result;
        }
    }
    async getArtistDevelopment(arg0: ArtistDevelopmentId): Promise<ArtistDevelopment> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistDevelopment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistDevelopment(arg0);
            return result;
        }
    }
    async getCallerArtistDevelopments(): Promise<Array<ArtistDevelopment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerArtistDevelopments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerArtistDevelopments();
            return result;
        }
    }
    async getCallerMemberships(): Promise<Array<Membership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMemberships();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMemberships();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPublishingWorks(): Promise<Array<PublishingWork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPublishingWorks();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPublishingWorks();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRecordingProjects(): Promise<Array<RecordingProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRecordingProjects();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRecordingProjects();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerReleases(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerReleases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerReleases();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangeHistory(arg0: string): Promise<Array<ChangeEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeHistory(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeHistory(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipDetails(arg0: MemberId): Promise<Membership> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipDetails(arg0);
                return from_candid_Membership_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipDetails(arg0);
            return from_candid_Membership_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfile(arg0: MemberId): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfile(arg0);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfile(arg0);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipProfilesByStatus(arg0: T): Promise<Array<MembershipProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipProfilesByStatus(to_candid_T_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishingWork(arg0: PublishingId): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishingWork(arg0);
                return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishingWork(arg0);
            return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordingProject(arg0: RecodingId): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordingProject(arg0);
                return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordingProject(arg0);
            return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelease(arg0: LabelEntityId): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelease(arg0);
            return result;
        }
    }
    async getRemainingRolloutSteps(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingRolloutSteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingRolloutSteps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateArtistDevelopment(arg0: ArtistDevelopmentId, arg1: CreateArtistDevelopmentRequest): Promise<ArtistDevelopment> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArtistDevelopment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArtistDevelopment(arg0, arg1);
            return result;
        }
    }
    async updateKnownUserRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKnownUserRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKnownUserRole();
            return result;
        }
    }
    async updateMembership(arg0: MemberId, arg1: string, arg2: string, arg3: T): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembership(arg0, arg1, arg2, to_candid_T_n49(this._uploadFile, this._downloadFile, arg3));
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembership(arg0, arg1, arg2, to_candid_T_n49(this._uploadFile, this._downloadFile, arg3));
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMembershipLinks(arg0: MemberId, arg1: Array<ArtistDevelopmentId>, arg2: Array<PublishingId>, arg3: Array<LabelEntityId>, arg4: Array<RecodingId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipLinks(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMembershipProfileFields(arg0: MemberId, arg1: string, arg2: string): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipProfileFields(arg0, arg1, arg2);
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipProfileFields(arg0, arg1, arg2);
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMembershipStatus(arg0: MemberId, arg1: T): Promise<MembershipProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipStatus(arg0, to_candid_T_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipStatus(arg0, to_candid_T_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_MembershipProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePublishingWork(arg0: PublishingId, arg1: CreatePublishingWorkRequest): Promise<PublishingWork> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublishingWork(arg0, to_candid_CreatePublishingWorkRequest_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublishingWork(arg0, to_candid_CreatePublishingWorkRequest_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PublishingWork_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecordingProject(arg0: RecodingId, arg1: CreateRecordingProjectRequest): Promise<RecordingProject> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecordingProject(arg0, to_candid_CreateRecordingProjectRequest_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecordingProject(arg0, to_candid_CreateRecordingProjectRequest_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_RecordingProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRelease(arg0: LabelEntityId, arg1: CreateReleaseRequest): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRelease(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRelease(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ChangeEvent_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangeEvent): ChangeEvent {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipProfile): MembershipProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Membership_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Membership): Membership {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PublishingWork_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishingWork): PublishingWork {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RecordingProject_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordingProject): RecordingProject {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SignedInUser_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignedInUser): SignedInUser {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_T_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    agreements: Array<string>;
    status: _T;
    updated_at: _Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: _Time;
    email: string;
    notes: string;
}): {
    id: MemberId;
    agreements: Array<string>;
    status: T;
    updated_at: Time;
    principal: Principal;
    name: string;
    tier: string;
    created_at: Time;
    email: string;
    notes: string;
} {
    return {
        id: value.id,
        agreements: value.agreements,
        status: from_candid_T_n12(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        principal: value.principal,
        name: value.name,
        tier: value.tier,
        created_at: value.created_at,
        email: value.email,
        notes: value.notes
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<_RecodingId>;
    owner: Principal;
    isrc: [] | [string];
    iswc: [] | [string];
    created_at: _Time;
    linkedReleases: Array<_LabelEntityId>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<_ArtistDevelopmentId>;
}): {
    id: PublishingId;
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    owner: Principal;
    isrc?: string;
    iswc?: string;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
} {
    return {
        id: value.id,
        title: value.title,
        ownershipSplits: value.ownershipSplits,
        linkedProjects: value.linkedProjects,
        owner: value.owner,
        isrc: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.isrc)),
        iswc: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.iswc)),
        created_at: value.created_at,
        linkedReleases: value.linkedReleases,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        registrationStatus: value.registrationStatus,
        contributors: value.contributors,
        linkedArtists: value.linkedArtists
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecodingId;
    status: _ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: _Time;
    owner: Principal;
    created_at: _Time;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    linkedArtists: Array<_ArtistDevelopmentId>;
}): {
    id: RecodingId;
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    owner: Principal;
    created_at: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        participants: value.participants,
        sessionDate: value.sessionDate,
        owner: value.owner,
        created_at: value.created_at,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        assetReferences: value.assetReferences,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        linkedArtists: value.linkedArtists
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedProjects: Array<_RecodingId>;
    tier: _MembershipTier;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    linkedArtists: Array<_ArtistDevelopmentId>;
    profile: _MembershipProfile;
}): {
    linkedProjects: Array<RecodingId>;
    tier: MembershipTier;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    linkedArtists: Array<ArtistDevelopmentId>;
    profile: MembershipProfile;
} {
    return {
        linkedProjects: value.linkedProjects,
        tier: value.tier,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        linkedArtists: value.linkedArtists,
        profile: from_candid_MembershipProfile_n10(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n32(_uploadFile, _downloadFile, value.role),
        profile: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    operationType: {
        link: null;
    } | {
        create: null;
    } | {
        update: null;
    };
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
}): {
    id: bigint;
    operationType: Variant_link_create_update;
    author: Principal;
    changedFields: Array<string>;
    timestamp: bigint;
    recordId: string;
} {
    return {
        id: value.id,
        operationType: from_candid_variant_n42(_uploadFile, _downloadFile, value.operationType),
        author: value.author,
        changedFields: value.changedFields,
        timestamp: value.timestamp,
        recordId: value.recordId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[_T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[_ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
}): {
    totalMemberships: bigint;
    membershipStatusCounts: Array<[T, bigint]>;
    totalRecordingProjects: bigint;
    projectStatusCounts: Array<[ProjectStatus, bigint]>;
    totalPublishingWorks: bigint;
    totalArtistDevelopment: bigint;
    releaseTypeCounts: Array<[string, bigint]>;
    totalReleases: bigint;
} {
    return {
        totalMemberships: value.totalMemberships,
        membershipStatusCounts: from_candid_vec_n45(_uploadFile, _downloadFile, value.membershipStatusCounts),
        totalRecordingProjects: value.totalRecordingProjects,
        projectStatusCounts: from_candid_vec_n47(_uploadFile, _downloadFile, value.projectStatusCounts),
        totalPublishingWorks: value.totalPublishingWorks,
        totalArtistDevelopment: value.totalArtistDevelopment,
        releaseTypeCounts: value.releaseTypeCounts,
        totalReleases: value.totalReleases
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n54(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_T, bigint]): [T, bigint] {
    return [
        from_candid_T_n12(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProjectStatus, bigint]): [ProjectStatus, bigint] {
    return [
        from_candid_ProjectStatus_n25(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
}): T {
    return "applicant" in value ? T.applicant : "active" in value ? T.active : "inactive" in value ? T.inactive : "paused" in value ? T.paused : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    archived: null;
}): ProjectStatus {
    return "in_progress" in value ? ProjectStatus.in_progress : "completed" in value ? ProjectStatus.completed : "planned" in value ? ProjectStatus.planned : "archived" in value ? ProjectStatus.archived : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    link: null;
} | {
    create: null;
} | {
    update: null;
}): Variant_link_create_update {
    return "link" in value ? Variant_link_create_update.link : "create" in value ? Variant_link_create_update.create : "update" in value ? Variant_link_create_update.update : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignedInUser>): Array<SignedInUser> {
    return value.map((x)=>from_candid_SignedInUser_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipProfile>): Array<MembershipProfile> {
    return value.map((x)=>from_candid_MembershipProfile_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublishingWork>): Array<PublishingWork> {
    return value.map((x)=>from_candid_PublishingWork_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecordingProject>): Array<RecordingProject> {
    return value.map((x)=>from_candid_RecordingProject_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Membership>): Array<Membership> {
    return value.map((x)=>from_candid_Membership_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChangeEvent>): Array<ChangeEvent> {
    return value.map((x)=>from_candid_ChangeEvent_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_T, bigint]>): Array<[T, bigint]> {
    return value.map((x)=>from_candid_tuple_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProjectStatus, bigint]>): Array<[ProjectStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n52(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePublishingWorkRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePublishingWorkRequest): _CreatePublishingWorkRequest {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateRecordingProjectRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRecordingProjectRequest): _CreateRecordingProjectRequest {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_T_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<RecodingId>;
    isrc?: string;
    iswc?: string;
    linkedReleases: Array<LabelEntityId>;
    linkedMembers: Array<MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<ArtistDevelopmentId>;
}): {
    title: string;
    ownershipSplits: Array<[string, bigint]>;
    linkedProjects: Array<_RecodingId>;
    isrc: [] | [string];
    iswc: [] | [string];
    linkedReleases: Array<_LabelEntityId>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    registrationStatus: string;
    contributors: Array<string>;
    linkedArtists: Array<_ArtistDevelopmentId>;
} {
    return {
        title: value.title,
        ownershipSplits: value.ownershipSplits,
        linkedProjects: value.linkedProjects,
        isrc: value.isrc ? candid_some(value.isrc) : candid_none(),
        iswc: value.iswc ? candid_some(value.iswc) : candid_none(),
        linkedReleases: value.linkedReleases,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        registrationStatus: value.registrationStatus,
        contributors: value.contributors,
        linkedArtists: value.linkedArtists
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: Time;
    linkedReleases: Array<LabelEntityId>;
    linkedWorks: Array<PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<MemberId>;
    notes: string;
    linkedArtists: Array<ArtistDevelopmentId>;
}): {
    status: _ProjectStatus;
    title: string;
    participants: Array<string>;
    sessionDate: _Time;
    linkedReleases: Array<_LabelEntityId>;
    linkedWorks: Array<_PublishingId>;
    assetReferences: Array<string>;
    linkedMembers: Array<_MemberId>;
    notes: string;
    linkedArtists: Array<_ArtistDevelopmentId>;
} {
    return {
        status: to_candid_ProjectStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        participants: value.participants,
        sessionDate: value.sessionDate,
        linkedReleases: value.linkedReleases,
        linkedWorks: value.linkedWorks,
        assetReferences: value.assetReferences,
        linkedMembers: value.linkedMembers,
        notes: value.notes,
        linkedArtists: value.linkedArtists
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    in_progress: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    archived: null;
} {
    return value == ProjectStatus.in_progress ? {
        in_progress: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.planned ? {
        planned: null
    } : value == ProjectStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    applicant: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
} {
    return value == T.applicant ? {
        applicant: null
    } : value == T.active ? {
        active: null
    } : value == T.inactive ? {
        inactive: null
    } : value == T.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
